name: Generate Content and Update Website

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression schedules it to run daily at midnight
  push:
    branches:
      - main  # This triggers the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install openai

    - name: Run generate_content.py to update index.html
      run: |
        python generate_content.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'github-actions'
        author_email: 'github-actions@github.com'
        message: 'Automated content update'

    - name: Push changes to GitHub
      run: git push
