name: Generate Blog Post

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run Python script to generate content
        run: |
          python generate_content.py

      - name: Commit and push the generated HTML
        run: |
          git add index.html
          git commit -m "Update index.html with AI content"
          git push
